// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package com.learn.netty.demo.grpc.idl;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 1;</code>
   */
  java.lang.String getRealname();
  /**
   * <code>string realname = 1;</code>
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
