// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package com.learn.netty.demo.grpc.idl;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
