// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package com.learn.netty.demo.grpc.idl;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestInfo = 1;</code>
   */
  java.lang.String getRequestInfo();
  /**
   * <code>string requestInfo = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestInfoBytes();
}
