// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package com.learn.netty.demo.grpc.idl;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseInfo = 1;</code>
   */
  java.lang.String getResponseInfo();
  /**
   * <code>string responseInfo = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseInfoBytes();
}
