// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package com.learn.netty.demo.grpc.idl;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.learn.netty.demo.grpc.idl.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .proto.StudentResponse studentResponse = 1;</code>
   */
  com.learn.netty.demo.grpc.idl.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.learn.netty.demo.grpc.idl.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .proto.StudentResponse studentResponse = 1;</code>
   */
  com.learn.netty.demo.grpc.idl.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
