// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package com.learn.netty.demo.grpc.idl;

public final class SutdentProto {
  private SutdentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Hello.proto\022\005proto\"\035\n\tMyRequest\022\020\n\010use" +
      "rname\030\001 \001(\t\"\036\n\nMyResponse\022\020\n\010realname\030\001 " +
      "\001(\t\"\035\n\016StudentRequest\022\013\n\003age\030\001 \001(\005\":\n\017St" +
      "udentResponse\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005" +
      "\022\014\n\004city\030\003 \001(\t\"F\n\023StudentResponseList\022/\n" +
      "\017studentResponse\030\001 \003(\0132\026.proto.StudentRe" +
      "sponse\"$\n\rStreamRequest\022\023\n\013requestInfo\030\001" +
      " \001(\t\"&\n\016StreamResponse\022\024\n\014responseInfo\030\001" +
      " \001(\t2\241\002\n\016StudentService\022>\n\025GetRealNameBy" +
      "Username\022\020.proto.MyRequest\032\021.proto.MyRes" +
      "ponse\"\000\022D\n\017GetStudentByAge\022\025.proto.Stude" +
      "ntRequest\032\026.proto.StudentResponse\"\0000\001\022L\n" +
      "\027GetStudensWrapperByAges\022\025.proto.Student" +
      "Request\032\026.proto.StudentResponse\"\000(\001\022;\n\006B" +
      "iTalk\022\024.proto.StreamRequest\032\025.proto.Stre" +
      "amResponse\"\000(\0010\001B/\n\035com.learn.netty.demo" +
      ".grpc.idlB\014SutdentProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MyResponse_descriptor,
        new java.lang.String[] { "Realname", });
    internal_static_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StudentRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StudentResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_proto_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StudentResponseList_descriptor,
        new java.lang.String[] { "StudentResponse", });
    internal_static_proto_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_proto_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_proto_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_proto_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
